import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Container } from '../components/container';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Strategie renderowania w <a href="https://nextjs.org">Next.js</a>
                    </h1>

                    <p className={styles.description}>Irek Róg</p>
                </main>
            </Container>
        </div>
    );
};

export default Home;
